// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNVlXh6OPwVvylqGvtqZslGbXct0QJR2A',
    appId: '1:271148732973:web:a65f2dab51364857765ea4',
    messagingSenderId: '271148732973',
    projectId: 'ereport-app-f0a14',
    authDomain: 'ereport-app-f0a14.firebaseapp.com',
    storageBucket: 'ereport-app-f0a14.firebasestorage.app',
    measurementId: 'G-8GFKL0Y08S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-dxmUmbIbU61ZIbDaQ05SaT2W9Gd95Tg',
    appId: '1:271148732973:ios:c84304276e425826765ea4',
    messagingSenderId: '271148732973',
    projectId: 'ereport-app-f0a14',
    storageBucket: 'ereport-app-f0a14.firebasestorage.app',
    iosBundleId: 'com.cmt.ereportapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-dxmUmbIbU61ZIbDaQ05SaT2W9Gd95Tg',
    appId: '1:271148732973:ios:c84304276e425826765ea4',
    messagingSenderId: '271148732973',
    projectId: 'ereport-app-f0a14',
    storageBucket: 'ereport-app-f0a14.firebasestorage.app',
    iosBundleId: 'com.cmt.ereportapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNVlXh6OPwVvylqGvtqZslGbXct0QJR2A',
    appId: '1:271148732973:web:d51f0aaf080ee729765ea4',
    messagingSenderId: '271148732973',
    projectId: 'ereport-app-f0a14',
    authDomain: 'ereport-app-f0a14.firebaseapp.com',
    storageBucket: 'ereport-app-f0a14.firebasestorage.app',
    measurementId: 'G-XTJ0B31FB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFS9i2SOVmZTR8JeWFcLBt92Z3N_Kj6Ag',
    appId: '1:271148732973:android:c04b2e2636b58bef765ea4',
    messagingSenderId: '271148732973',
    projectId: 'ereport-app-f0a14',
    storageBucket: 'ereport-app-f0a14.firebasestorage.app',
  );

}